# Generated by Django 5.0.1 on 2024-02-18 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='pupils',
        ),
        migrations.AddField(
            model_name='pupil',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupils', to='core.grade', verbose_name='Класс'),
        ),
    ]
